#!/bin/bash

./lm-dict -f 0.3 \
    $HOME/data/uw3/book/????.gt.txt \
    $HOME/data/unlv/book/????.gt.txt \
    $HOME/data/reuters/*.sgm \
    /usr/share/dict/words \
    $HOME/data/names/allnames.txt \
    <(cat /usr/share/dict/words | tr a-z A-Z) \
    <(cat /usr/share/dict/words | tr A-Z a-z) \
    /dev/null
