#!/usr/bin/python

import sys,os,re,glob,math,glob,signal,traceback
import matplotlib
from collections import Counter
import argparse
from math import log

parser = argparse.ArgumentParser(description = """
""")
parser.add_argument("-o","--output",default="none.fst")
args = parser.parse_args()

import openfst
def Fst():
    return openfst.StdVectorFst()

sigma = -3
fst = Fst()
state = fst.AddState()
fst.SetStart(state)
fst.SetFinal(state,0.0)
fst.AddArc(state,sigma,sigma,0.0,state)
fst.Write(args.output)
