#!/bin/bash

sudo apt-get install \
    build-essential imagemagick scons mercurial \
    libpng12-dev libjpeg8-dev libtiff4-dev libgif-dev \
    libsdl-gfx1.2-dev libsdl-image1.2-dev libsdl1.2-dev \
    libavcodec-dev libavdevice-dev libavformat-dev libavutil-dev \
    libavfilter-dev \
    libpng12-dev libjpeg8-dev libtiff4-dev libgif-dev \
    libsdl-gfx1.2-dev libsdl-image1.2-dev libsdl1.2-dev \
    libavcodec-dev libavdevice-dev libavformat-dev libavutil-dev \
    libavfilter-dev \
    libgsl0-dev libblas-dev \
    libsqlite3-dev\
    liblapack-dev libatlas-base-dev \
    python-dev swig2.0 swig zlib1g-dev \
    python-scipy python-matplotlib python-matplotlib-data \
    python-sklearn \
    python-tables \
    ipython ipython-notebook
