#!/usr/bin/python

import signal
signal.signal(signal.SIGINT,lambda *args:sys.exit(1))
import sys,os,re,optparse,shutil
from matplotlib import patches
from pylab import *
from scipy.stats.stats import trim1

from scipy.ndimage import measurements
from scipy.misc import imsave
from PIL import Image
import ocropy
from ocropy import N,NI

parser = optparse.OptionParser(usage="""
%prog [options] book/????.png

Puts together the result of OCR steps into an XHTML output file.
Uses...

- 0001.png 
- 0001.bin.png
- 0001.pseg.png
- 0001/010001.txt
- 0001/010001.cseg.png

etc.
""")
parser.add_option("-b","--breaks",action="store_true",
                  help="output line breaks")
options,args = parser.parse_args()

header = """
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>OCR Results</title>
<meta name="Description" content="OCRopus Output" />
</head>
<body>
"""
footer = """
</body>
</html>
"""

def E(*args):
    sys.stderr.write(" ".join(args))
    sys.stderr.write("\n")
def P(*args):
    print "".join(args)

P(header)

for arg in args:
    base,_ = ocropy.allsplitext(arg)
    pseg = ocropy.intarray()
    try:
        P("<div class='ocr_page' title='file %s'>"%arg)
        if not os.path.exists(base+".pseg.png"):
            E("%s: no such file"%(base+".pseg.png",))
            continue
        if not os.path.isdir(base):
            E("%s: no such directory"%base)
            continue
        ocropy.read_image_packed(pseg,base+".pseg.png")
        ocropy.make_page_segmentation_black(pseg)
        regions = ocropy.RegionExtractor()
        regions.setPageLines(pseg)
        for i in range(1,regions.length()):
            id = regions.id(i)
            x0,y0,x1,y1 = (regions.x0(i),regions.y0(i), regions.x1(i),regions.y1(i))
            lbase = "%s/%06x"%(base,id)
            if not os.path.exists(lbase+".txt"):
                E("%s: no such file"%(lbase+".txt"))
                continue
            with open(lbase+".txt") as stream:
                text = stream.read()
            text = re.sub(r'\&','\&amp;',text)
            text = re.sub(r'\<','\&lt;',text)
            P("<span class='ocr_line' title='bbox %d %d %d %d'>"%(x0,y0,x1,y1),text,"</span>")
            if options.breaks:
                P("<br />")
    finally:
        P("</div>")

P(footer)
