#!/usr/bin/python
import code,pickle,sys,os,re
from optparse import OptionParser
from pylab import *
import ocropy
from ocropy import dbtables,binnednn,ocrobook
from ocropy.utils import Record

parser = OptionParser("""
usage: %prog [options] .../.../010001.png ...

Extract character images from OCR output and store them in a database file.  
This assume that for each line.png, there is a line.cseg.gt.png and line.gt.txt file.
""")

parser.add_option("-o","--output",help="output file",default="chars.db")
parser.add_option("-u","--unmerged",help="unmerged output file",default=None)
parser.add_option("-m","--missegmented",help="output missegmented characters",action="store_true")
parser.add_option("-r","--raw",help="output unlabeled characters",action="store_true")
parser.add_option("-a","--maxage",help="output missegmented",default=10000000,type="int")

parser.add_option("-D","--display",help="display chars",action="store_true")
parser.add_option("-v","--verbose",help="verbose output",action="store_true")
parser.add_option("-N","--nosource",help="do not record source info",action="store_true")
parser.add_option("-S","--segmenter",help="segmenter",default="DpSegmenter")

(options,args) = parser.parse_args()

if len(args)<1:
    parser.print_help()
    sys.exit(0)

ion()
show()

if os.path.exists(options.output):
    print options.output,"exists; please remove"
    sys.exit(1)

table = dbtables.Table(options.output,"chars")
table.converter("image",dbtables.SmallImage())
table.create(image="blob",cls="text",file="text",segid="integer",bbox="text",count="integer",classes="text")

segmenter = None
if options.segmenter!="none":
    segmenter = ocropy.make_ISegmentLine(options.segmenter)

class BadGroundTruth(Exception):
    pass

def cseg_chars(file,suffix=".gt"):
    image = ocropy.bytearray()
    ocropy.read_image_gray(image,file)
    ocropy.sub(255,image)
    base,_ = ocropy.allsplitext(file)
    cseg = ocropy.intarray()
    ocropy.read_image_packed(cseg,base+".cseg"+suffix+".png")
    ocropy.make_line_segmentation_black(cseg)
    with open(base+suffix+".txt") as stream:
        gt = stream.read()
    gt = re.sub('\n','',gt)
    grouper = ocropy.make_IGrouper("SimpleGrouper")
    grouper.pset("maxrange",1)
    grouper.setSegmentation(cseg)
    print grouper.length(),len(gt),len(re.sub(' ','',gt))
    if len(gt)!=grouper.length():
        gt = re.sub(' ','',gt)
        if len(gt)!=grouper.length():
            raise BadGroundTruth()
    for i in range(grouper.length()):
        cls = gt[i]
        if cls==' ': continue
        raw = ocropy.bytearray()
        mask = ocropy.bytearray()
        grouper.extractWithMask(raw,mask,image,i,1)
        yield Record(raw=raw,mask=mask,cls=cls,index=i,bbox=grouper.boundingBox(i))

ntried = 0
nfiles = 0
total = 0
for file in args:
    segments = []
    text = ""
    ntried += 1
    try:
        items = list(cseg_chars(file))
        nfiles += 1
    except IOError,e:
        print "ERROR",e
        print "# cseg for",file,"not found (got %d of %d files)"%(nfiles,ntried)
        continue
    except:
        print "#",file,"failed"
        continue
    if options.verbose:
        print file,len(segments),len(text)
    index = 0
    for x in items:
        raw = x.raw
        mask = x.mask
        cls = x.cls
        print index,cls
        index += 1
        segments.append(raw)
        if options.display:
            clf(); gray(); imshow(ocrobook.NI(raw)); draw()
        text += cls
        if cls is None:
            # no ground truth
            if not options.raw: continue
            cls = "_"
        elif cls<=0 or cls=="":
            # missegmented
            if not options.missegmented: continue
            cls = "~"
        raw = ocrobook.NI(raw)
        if raw.shape[0]>255 or raw.shape[1]>255: continue
        raw = raw/float(amax(raw))
        key = re.sub(r'^.*/(\d\d\d\d/)','\\1',file)
        key = re.sub(r'\.png$','',key)
        if options.verbose:
            print key,cls,raw.shape
        if options.nosource:
            id = table.set(image=raw,cls=cls,count=1)
        else:
            r = x.bbox
            id = table.set(image=raw,cls=cls,count=1,
                           file=file,
                           bbox="%d %d %d %d"%(r.x0,r.y0,r.x1,r.y1))
        total+=1
        if total%10000==0:
            print total,"chars"
            table.commit()

table.commit()
print total,"chars"
