#!/bin/bash -e

BASE=$(dirname "$0")

rm -rf temp 
ocropus-nlbin "$BASE"/tests/testpage.png -o temp
ocropus-gpageseg 'temp/????.bin.png'
ocropus-rpred --parallel=0 --nocheck 'temp/0001/01000?.bin.png'
ocropus-hocr 'temp/????.bin.png' -o temp.html 2>/dev/null
ocropus-visualize-results temp
ocropus-gtedit html temp/????/??????.bin.png -o temp-correction.html
