#!/bin/sh

model=full-300-10-40r.cmodel 

find unlv/. uw3/. | egrep '/......\.rseg\.png$' | xargs -r rm 
find unlv/. uw3/. | egrep '/......\.fst$' | xargs -r rm 

$HOME/ocropus/ocropy/ocropus-lattices -m $model unlv uw3
