#!/bin/bash -e

set -x

rm -rf temp 
mkdir temp
cp tests/testpage.png temp/0001.png

true
true binarization
true

ocropus-nlbin 'temp/????.png'

true
true page level segmentation
true

ocropus-gpageseg 'temp/????.png'

true
true raw text line recognition
true

ocropus-lattices --parallel=3 'temp/????/??????.png'

true
true language model application
true

ocropus-ngraphs 'temp/????/??????.lattice'

true
true create hOCR output
true

ocropus-hocr 'temp/????.png' > temp.html

true
true 'create HTML for debugging (use "firefox temp/index.html" to view)'
true

ocropus-genhtml temp

true
true "to see recognition results, type: firefox temp.html"
true "to see details on the recognition process, type: firefox temp/index.html"
true
