#!/bin/bash -e

BASE=$(dirname $0)

# 'RUNNER' is the binary that the scripts are executed by. It defaults to
# 'python2' if not set in the environment.
# Other examples:
#       PATH=$PWD:$PATH RUNNER='python2 -m coverage run --include=$PWD/**/*' ./run-test
#       PATH=$PWD:$PATH RUNNER='python3' ./run-test
# See ./run-coverage for a real example.
RUNNER="${RUNNER:-python2}"

test_page() {
    set -x
    $RUNNER "$BASE/ocropus-nlbin $BASE/tests/testpage.png" -o temp
    $RUNNER "$BASE/ocropus-gpageseg" 'temp/????.bin.png'
    $RUNNER "$BASE/ocropus-rpred" --parallel=0 --nocheck  'temp/0001/01000?.bin.png'
    $RUNNER "$BASE/ocropus-hocr" 'temp/????.bin.png' -o temp.html 2>/dev/null
    $RUNNER "$BASE/ocropus-visualize-results" temp
    $RUNNER "$BASE/ocropus-gtedit html" temp/????/??????.bin.png -o temp-correction.html
    set +x
    echo "#     to see recognition results, type: firefox temp.html"
    echo "#     to see correction page, type: firefox temp-correction.html"
    echo "#     to see details on the recognition process, type: firefox temp/index.html"
}

test_conf() {
    local TESTIMAGE=0079-01000d
    mkdir -p temp
    cp "$BASE/tests/$TESTIMAGE"* temp
    set -x
    $RUNNER ocropus-rpred temp/$TESTIMAGE.png
    $RUNNER ocropus-errs  temp/$TESTIMAGE.gt.txt
    $RUNNER ocropus-econf temp/$TESTIMAGE.gt.txt
}

rm -rf temp
test_page
test_conf
