#!/bin/sh

model=full-300-10-40r.cmodel 

find book | egrep 'book/..../......\.(txt|fst|cseg\.png|rseg\.png|gt\.png|gt.fst)$' | xargs -r rm -v

$HOME/ocropus/ocropy/ocropus-lattices -m $model unlv uw3
