#!/bin/bash -e

COVERAGE="python2 -m coverage"

rm -rf .coverage*
PATH=$PWD:$PATH RUNNER="$COVERAGE run -p --include=$PWD/**/*" ./run-test
$COVERAGE combine
rm -rf htmlcov
$COVERAGE html
echo "#     to see coverage results, browse to file://$PWD/htmlcov/index.html"
