#!/usr/bin/env python

from ocrolib import edist
def testLevenshtein(a, b, should):
    if edist.levenshtein(a, b) == should:
        print 'ok - levenshtein(%s, %s) == %s' % (a,b,should)
    else:
        print 'not ok - levenshtein(%s, %s) == %s' % (a,b,should)
testLevenshtein('a', 'a', 0)
testLevenshtein('', '', 0)
testLevenshtein('a', '', 1)
testLevenshtein('', 'a', 1)
testLevenshtein('aa', 'aaaaaa', 4)
