import os
import distutils.sysconfig

prefix = ARGUMENTS.get('prefix', "/usr/local")
env = Environment()
if ARGUMENTS.get('debug',0):
    env.Append(CXXFLAGS="--std=c++11 -g -fno-inline".split())
else:
    env.Append(CXXFLAGS="--std=c++11 -g -O3 -finline".split())
env.Append(CPPPATH=["/usr/include/eigen3"])
env.Append(LIBS=["hdf5_cpp","hdf5"])

libclstm = env.StaticLibrary("clstm", source = ["clstm.cc"])

Alias('install-lib', Install(os.path.join(prefix,"lib"), libclstm))
Alias('install-include', Install(os.path.join(prefix,"include"), ["clstm.h"]))
Alias('install',['install-lib', 'install-include'])

env.Program("clstmctc",
            ["clstmctc.cc"],
            LIBS=[libclstm,"hdf5_cpp","hdf5","zmqpp","zmq"])
env.Program("clstmseq",
            ["clstmseq.cc"],
            LIBS=[libclstm,"hdf5_cpp","hdf5","zmqpp","zmq"])
